### ISSUE TITLE
Bug: Minimum version of symfony/process causes fatal error

### ISSUE THREAD

**Issue by JPry** [weprovide/valet-plus#587]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.2.1`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
PR #585 introduced the use of `Process::fromShellCommandline()`. However, the version constraints of the `symfony/process` component in `composer.json` allow for versions of the `process` component that do not have this method. Specifically, it seems to have been introduced in version 4+, so version 2 and 3 cause the error.

When running any `valet` command with an older version of the `process` component installed, a fatal error will occur:

```
valet restart

PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php:78
Stack trace:
#0 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php(63): Valet\CommandLine->runCommand('sudo -u jpry br...', Object(Closure))
#1 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/Brew.php(33): Valet\CommandLine->runAsUser('brew list --for...')
#2 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/Brew.php(191): Valet\Brew->installed('dnsmasq')
#3 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/DnsMasq.php(151): Valet\Brew->restartService(Array)
#4 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/includes/facades.php(28): Valet\DnsMasq->restart()
#5 /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php(358): Facade::__callStatic('restart', Array)
#6 [internal function]: Silly\Application->{closure}(Array)
#7 /Users/jpry/.composer/vendor/php-di/invo in /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php on line 78

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php on line 78

Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php on line 78

Call Stack:
    0.0033     395264   1. {main}() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php:0
    0.0413    1235920   2. Silly\Application->run() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php:969
    0.0493    1326240   3. Silly\Application->doRun() /Users/jpry/.composer/vendor/symfony/console/Application.php:148
    0.0495    1329616   4. Silly\Application->doRunCommand() /Users/jpry/.composer/vendor/symfony/console/Application.php:255
    0.0495    1329616   5. Silly\Command\Command->run() /Users/jpry/.composer/vendor/symfony/console/Application.php:992
    0.0497    1331448   6. Silly\Application->Silly\{closure:/Users/jpry/.composer/vendor/mnapoli/silly/src/Application.php:70-93}() /Users/jpry/.composer/vendor/symfony/console/Command/Command.php:253
    0.0497    1332784   7. Invoker\Invoker->call() /Users/jpry/.composer/vendor/mnapoli/silly/src/Application.php:85
    0.0497    1333352   8. call_user_func_array:{/Users/jpry/.composer/vendor/php-di/invoker/src/Invoker.php:82}() /Users/jpry/.composer/vendor/php-di/invoker/src/Invoker.php:82
    0.0498    1333368   9. Silly\Application->{closure:/Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php:356-401}() /Users/jpry/.composer/vendor/php-di/invoker/src/Invoker.php:82
    0.0498    1333368  10. Facade::restart() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php:358
    0.0498    1333368  11. Facade::__callStatic() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/valet.php:358
    0.0514    1336048  12. Valet\DnsMasq->restart() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/includes/facades.php:28
    0.0514    1336048  13. Valet\Brew->restartService() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/DnsMasq.php:151
    0.0514    1336424  14. Valet\Brew->installed() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/Brew.php:191
    0.0514    1336488  15. Valet\CommandLine->runAsUser() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/Brew.php:33
    0.0514    1336568  16. Valet\CommandLine->runCommand() /Users/jpry/.composer/vendor/weprovide/valet-plus/cli/Valet/CommandLine.php:63

```

**What was supposed to happen?**
The command should run without an error.

**What actually happened?**
A fatal error occurs.

**How to reproduce this?**
Install Valet+ (`composer install`) with the following `composer.json` file:

```json
{
    "require": {
        "symfony/process": "^3",
        "weprovide/valet-plus": "^2.1"
    },
}
```

Afterwards, try to run a `valet` command, such as `valet restart`

**What is the solution?**
Update the `composer.json` requirements in this repository to remove the allowance of versions 2 and 3 of `symfony/process`.

**Comment by diazwatson** [comment]
This solved my issue

**Comment by mischabraam** [comment]
I've built in a fallback.

```
        $process = null;
        if (is_callable(Process::class, 'fromShellCommandline')) {
            $process = Process::fromShellCommandline($command);
        } else {
            $process = new Process($command);
        }
```

I've had feedback this doesn't work :(

**Comment by mischabraam** [comment]
@JPry please see https://github.com/weprovide/valet-plus/pull/598. Can you let me know if this works?

**Comment by JPry** [comment]
@mischabraam I left a comment on the PR. It needs to be version 4.2+ to fix this issue, or else the use of `::fromShellCommandline` needs to be removed.

**Comment by mischabraam** [comment]
Thanks! I updated the PR, but I'm kinda scared it will break things. It needs proper testing, can you help with that?

**Comment by mischabraam** [comment]
Fixed in v3
