### ISSUE TITLE
MySQL error (HY000/2002)

### ISSUE THREAD

**Issue by Aekal** [weprovide/valet-plus#81]
I installed valet by following the instructions without any problems, but when i'm trying to create a new database or show a list by typing `valet db ls` I get an error:
```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 172
Failed to connect to database

Warning: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given in /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 233

Fatal error: Uncaught Error: Call to a member function query() on boolean in /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php:234
Stack trace:
#0 /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php(256): Valet\Mysql->getDatabases()
#1 /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/includes/facades.php(28): Valet\Mysql->listDatabases()
#2 /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/valet.php(428): Facade::__callStatic('listDatabases', Array)
#3 [internal function]: Silly\Application->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 'ls', NULL, NULL)
#4 /Users/aekal/.composer/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#5 /Users/aekal/.composer/vendor/mnapoli/silly/src/Application.php(85): Invoker\Invoker->call(Object(Closure), Array)
#6 [internal function]: Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfo in /Users/aekal/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 234
```

I tried to reinstall mysql and install valet again, but it didn't help.

**Comment by abdodaoud** [comment]
I'm facing the same issue :(

**Comment by SanderAtom** [comment]
Did you have MySQL installed before installing valet+? Because it's failing to connect to your mysql on localhost:
`$link = new mysqli('localhost', 'root', 'root');`

**Comment by Aekal** [comment]
I completely removed MySQL ([using these instructions](https://gist.github.com/vitorbritto/0555879fe4414d18569d)) before installing valet+. I read that 
> Valet+ automatically installs MySQL 5.7 with 5.6 compatibility mode included.

**Comment by rafaelstz** [comment]
I solved it running these commands:

```bash
valet uninstall
valet install 
valet fix
/usr/local/Cellar/mysql@5.7/5.7.29/bin/mysql.server start
```
